/**
 * ⚙️ GroupCard 区域常量
 */

export const CARD_CONSTANTS = {
  HEIGHT: 200,
  AVATAR_SIZE: 40,
  MAX_TAGS: 3,
  MAX_PARTICIPANTS_DISPLAY: 5,
  TITLE_MAX_LENGTH: 20,
  LOCATION_MAX_LENGTH: 25,
  PARTICIPANT_AVATAR_SIZE: 24,
  PARTICIPANT_AVATAR_OVERLAP: -8,
} as const;
