/**
 * ⚙️ TypeGrid 区域常量
 */

export const TYPE_GRID_CONSTANTS = {
  CARD_ASPECT_RATIO: 1,
  CARD_SPACING: 8,
  GRID_COLUMNS: 3,
  ANIMATION_DURATION: 200,
  SCALE_FACTOR: 0.95,
  SELECTED_BORDER_WIDTH: 3,
  SHADOW_ELEVATION: 5,
  SELECTED_SHADOW_ELEVATION: 8,
} as const;