/**
 * ⚙️ QuickFilters 区域常量
 */

export const QUICK_FILTER_CONSTANTS = {
  SORT_BUTTON_MIN_WIDTH: 80,
  GENDER_BUTTON_MIN_WIDTH: 70,
  ADVANCED_BUTTON_MIN_WIDTH: 60,
  BUTTON_HEIGHT: 32,
  FILTER_DEBOUNCE: 300,
  MAX_FILTER_TEXT_LENGTH: 10,
} as const;
